# Generated by Django 2.1.2 on 2018-12-04 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=50)),
                ('goods_type', models.CharField(max_length=20)),
                ('goods_introduce', models.CharField(max_length=150)),
                ('goods_shelf_life', models.DateField(blank=True)),
                ('goods_warranty', models.DateField()),
                ('goods_product_parameters', models.CharField(max_length=500)),
                ('goods_unit_price', models.FloatField()),
                ('goods_inventory', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_account', models.CharField(max_length=50)),
                ('manager_password', models.CharField(max_length=16)),
                ('manager_name', models.CharField(max_length=10)),
                ('manager_create', models.DateField(auto_now_add=True)),
                ('manager_gender', models.CharField(max_length=2)),
                ('manager_address', models.CharField(max_length=30)),
                ('manager_access', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('merchants_id', models.AutoField(primary_key=True, serialize=False)),
                ('merchants_name', models.CharField(max_length=50)),
                ('merchants_create_time', models.DateField(auto_now_add=True)),
                ('merchants_type', models.CharField(max_length=10)),
                ('merchants_address', models.CharField(max_length=30)),
                ('my_goods', models.ManyToManyField(to='ebapp.Goods')),
                ('my_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebapp.Managers')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(max_length=2)),
                ('my_goods', models.ManyToManyField(to='ebapp.Goods')),
                ('my_merchants', models.ManyToManyField(to='ebapp.Merchants')),
            ],
        ),
        migrations.CreateModel(
            name='RefillLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoppingcart_create_time', models.DateField(auto_now_add=True)),
                ('goods_product_parameters', models.CharField(max_length=50)),
                ('my_goods', models.ManyToManyField(to='ebapp.Goods')),
                ('my_merchants', models.ManyToManyField(to='ebapp.Merchants')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecords',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_create_time', models.DateField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=2)),
                ('transaction_finish_time', models.DateField(auto_now=True)),
                ('my_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebapp.Goods')),
                ('my_merchants', models.ManyToManyField(to='ebapp.Merchants')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_account', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=16)),
                ('user_name', models.CharField(max_length=10)),
                ('user_create', models.DateField(auto_now_add=True)),
                ('user_nick_name', models.CharField(max_length=20)),
                ('user_gender', models.CharField(max_length=2)),
                ('user_birthday', models.DateField()),
                ('user_address', models.CharField(max_length=30)),
                ('user_receiving_address', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='transactionrecords',
            name='my_user',
            field=models.ManyToManyField(to='ebapp.Users'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='my_user',
            field=models.ManyToManyField(to='ebapp.Users'),
        ),
        migrations.AddField(
            model_name='order',
            name='my_user',
            field=models.ManyToManyField(to='ebapp.Users'),
        ),
        migrations.AddField(
            model_name='goods',
            name='my_merchants',
            field=models.ManyToManyField(to='ebapp.Merchants'),
        ),
    ]
