# Generated by Django 2.2 on 2019-04-14 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=64)),
                ('introduce', models.TextField()),
                ('shelf_life', models.DateField(null=True)),
                ('warranty', models.DateField(null=True)),
                ('product_param', models.TextField()),
                ('price', models.FloatField()),
                ('inventory', models.FloatField()),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=4)),
                ('address', models.CharField(max_length=30)),
                ('access', models.CharField(choices=[('o_manager', '订单管理员'), ('t_manager', '交易管理员'), ('s_manager', '商户管理员')], default='订单管理员', max_length=32)),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('c_time', models.DateField(auto_now_add=True)),
                ('type', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('my_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebapp.Goods')),
                ('my_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebapp.Managers')),
            ],
            options={
                'verbose_name': '商户',
                'verbose_name_plural': '商户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('nick_name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=4)),
                ('birth', models.DateField(null=True)),
                ('address', models.CharField(max_length=30)),
                ('receive_address', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='TransactionRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('start', '交易开始'), ('finish', '交易结束')], default='交易结束', max_length=32)),
                ('f_time', models.DateField(auto_now=True)),
                ('my_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebapp.Goods')),
                ('my_merchants', models.ManyToManyField(to='ebapp.Merchants')),
                ('my_user', models.ManyToManyField(to='ebapp.Users')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True)),
                ('count', models.IntegerField()),
                ('my_goods', models.ManyToManyField(to='ebapp.Goods')),
                ('my_merchants', models.ManyToManyField(to='ebapp.Merchants')),
                ('my_user', models.ManyToManyField(to='ebapp.Users')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('start', '订单开始'), ('finish', '订单结束')], default='交易结束', max_length=32)),
                ('c_time', models.DateField(auto_now_add=True)),
                ('f_time', models.DateField(auto_now=True)),
                ('my_goods', models.ManyToManyField(to='ebapp.Goods')),
                ('my_merchants', models.ManyToManyField(to='ebapp.Merchants')),
                ('my_user', models.ManyToManyField(to='ebapp.Users')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='my_merchants',
            field=models.ManyToManyField(to='ebapp.Merchants'),
        ),
    ]
