# Generated by Django 2.1.2 on 2018-12-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0002_auto_20181207_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_password',
            field=models.CharField(max_length=10000),
        ),
    ]
