# Generated by Django 2.1.2 on 2018-12-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0004_auto_20181207_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_birthday',
            field=models.DateField(blank=True),
        ),
    ]
